MyFlyer.Web/Areas/Admin/Models/FlyerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFlyer.Web.Areas.Admin.Models
{
    public class FlyerViewModel
    {
        [Required]
        public string Url { get; set; }
        [Display(Name = "Valid From")]
        [DataType(DataType.Date)]
        public DateTime Valid_from { get; set; }
        [Display(Name = "Valid To")]
        [DataType(DataType.Date)]
        public DateTime Valid_to { get; set; }

    }
}

MyFlyer.Web/Areas/Admin/Controllers/FlyerManager/FlyerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFlyer.Data.Interfaces;
using MyFlyer.Service;
using MyFlyer.Web.Areas.Admin.Models;
using MyFlyer.Web.Models.DataModel;
using MyFlyer.Model.Entities;
using Microsoft.AspNetCore.Authorization;

namespace MyFlyer.Web.Areas.Admin.Controllers.FlyerManager
{
    [Area("admin")]
    [Authorize(Roles ="Admin")]
    public class FlyerController : Controller
    {
        private readonly IFlyerRepository _flyerRepository;
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryReposity;
        private readonly IMerchantRepository _merchantRepository;
        private readonly IMerchantCategoryRepo _merchantCategoryRepo;

        public FlyerController(IFlyerRepository flyerRepository, IProductRepository productRepository, ICategoryRepository categoryReposity, IMerchantRepository merchantRepository, IMerchantCategoryRepo merchantCategoryRepo)
        {
            _flyerRepository = flyerRepository;
            _productRepository = productRepository;
            _categoryReposity = categoryReposity;
            _merchantRepository = merchantRepository;
            _merchantCategoryRepo = merchantCategoryRepo;
        }


        // GET: Flyer
        public ActionResult Index()
        {
            var flyers = _flyerRepository.GetAll();
            return View(flyers);
        }

        // GET: Flyer/Details/5
        public ActionResult Delete(int id)
        {

            _flyerRepository.Delete(id);
            return RedirectToAction("Index");
        }


        // GET: Flyer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Flyer/Create

        [HttpPost]
        [Obsolete]
        public ActionResult Create(string url)
        {
            if (!ModelState.IsValid)
            {
                return View(url);
            }
            else
            {
                var flyerViewModel = new FlyerViewModel
                {
                    Url = url
                };

                if (!_flyerRepository.IsExist(f => f.Url == url))
                {
                    var crawlObject = Function.GetAllCrawlModels(url);
                    var merchant = new Merchant
                    {
                        Name = crawlObject.merchant,
                        Url = crawlObject.merchant_url,
                        LogoFile = crawlObject.merchant_logo
                    };
                    if (!_merchantRepository.IsExist(m => m.Name == merchant.Name))
                    {
                        _merchantRepository.Add(merchant);
                    }
                    else
                    {
                        merchant = _merchantRepository.GetByCondition(m => m.Name == merchant.Name).FirstOrDefault();
                    }

                    foreach (var crawlcate in crawlObject.categories)
                    {
                        var category = new Category();
                        category.Name = crawlcate.name;                       

                        if (!_categoryReposity.IsExist(c => c.Name == category.Name))
                        {
                            _categoryReposity.Add(category);
                        }
                        else
                        {
                            category = _categoryReposity.GetByCondition(c => c.Name == category.Name).FirstOrDefault();
                        }
                        var merchantCategory = new MerchantCategory
                        {
                            Merchant = merchant,
                            Category = category
                        };
                        var exist = _merchantCategoryRepo.GetByCondition(c => c.Category == category & c.Merchant == merchant).Count > 0 ? true : false;
                        if (!exist)
                        {
                            _merchantCategoryRepo.Add(merchantCategory);
                            merchant.MerchantCategories.Add(merchantCategory);
                            category.MerchantCategories.Add(merchantCategory);
                        }
                    }

                    foreach (var item in crawlObject.items)
                    {
                        if (item.current_price != null)
                        {
                            var product = new Product
                            {
                                Name = item.name,
                                CurrentPrice = Convert.ToDecimal(item.current_price),
                                Brand = item.brand,
                                Description = item.description,
                                Discount_percent = item.discount_percent.ToString(),
                                DisplayName = item.display_name,
                                Dist_coupon_image_url = item.dist_coupon_image_url,
                                Image = item.large_image_url,
                                Url = item.url,
                                InStoreOnly = item.in_store_only,
                                X_large_image_url = item.x_large_image_url,
                                Sale_Story = item.sale_story,
                                Item_Id = item.flyer_item_id,
                                Valid_from = DateTime.Parse(item.valid_from),
                                Valid_to = DateTime.Parse(item.valid_to)
                            };

                            if (item.category_names.Count > 0)
                            {                                
                                var cate = item.category_names[0];
                                var proCate = _categoryReposity.GetByCondition(c => c.Name ==cate).FirstOrDefault();
                                if (proCate == null)
                                {
                                    proCate = new Category();
                                    proCate.Name = cate;
                                    _categoryReposity.Add(proCate);
                                }
                                    var merchantCategory = new MerchantCategory
                                    {
                                        Merchant = merchant,
                                        Category = proCate
                                    };
                                    var exist = _merchantCategoryRepo.GetByCondition(c => c.Category == proCate & c.Merchant == merchant).Count > 0 ? true : false;
                                    if (!exist)
                                    {
                                        _merchantCategoryRepo.Add(merchantCategory);
                                        merchant.MerchantCategories.Add(merchantCategory);
                                        proCate.MerchantCategories.Add(merchantCategory);
                                    }
                                
                                product.Category = proCate;
                                
                            }
                            if (!_productRepository.IsExist(p => p.Item_Id == product.Item_Id))
                            {
                                _productRepository.Add(product);
                                if (!merchant.Products.Contains(product))
                                {
                                    merchant.Products.Add(product);
                                }
                            }
                        }
                    }
                    _merchantRepository.Update(merchant);
                    var flyer = new Flyer
                    {
                        Url = url,
                        Valid_from = crawlObject.valid_from,
                        Valid_to = crawlObject.valid_to
                    };
                    _flyerRepository.Add(flyer);
                }
            }
            return View();
        }

       
       
    }
}

MyFlyer.Web/Areas/Admin/Views/Flyer/Create.cshtml
@model MyFlyer.Web.Areas.Admin.Models.FlyerViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div>
        <div class="container">
            <div class="row clearfix">
                <h3>Create Data</h3>
                <div class="col-md-11 col-md-offset-3 column">
                    <form asp-action="Create" method="POST" asp-area="Admin" asp-controller="Flyer">
                        <div class="form-group">
                            <label asp-for="Url"></label>
                            <input type="text" class="form-control" asp-for="Url" />
                            <span class="text-danger" asp-validation-for="Url"></span>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>

MyFlyer.Web/Areas/Admin/Views/Flyer/Index.cshtml
@model IEnumerable<MyFlyer.Model.Entities.Flyer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valid_from)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valid_to)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valid_from)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valid_to)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
               <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MyFlyer.Web/Areas/Admin/Views/Flyer/View.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>